import { color } from "@/styles/variable/indexStyle";

const lightStatus = {
  connect: {
    color: color.red,
  },
  disConnect: {
    color: color.green,
  },
  trip: {
    color: color.yellow,
  },
};
const equipmentStatusList = [
  { text: "投入", lightType: lightStatus.connect },
  { text: "切離", lightType: lightStatus.disConnect },
  { text: "跳脫", lightType: lightStatus.trip },
];
// 設備狀態
const equipmentVcpList = [
  {
    itemList: [{ text: "MVCP", lightStatus: "connect" }],
    title: "MVCP-1",
  },
  {
    itemList: [{ text: "MVCP", lightStatus: "connect" }],
    title: "MVCP-2",
  },
  {
    itemList: [
      { text: "A-VCP", lightStatus: "connect" },
      { text: "A-GCB 1", lightStatus: "connect" },
      { text: "A-GCB 2", lightStatus: "connect" },
      { text: "A-GCB 3", lightStatus: "connect" },
      { text: "A-LBS", lightStatus: "connect" },
      { text: "A-ACB 1", lightStatus: "connect" },
      { text: "A-ACB 2", lightStatus: "connect" },
      { text: "A-ACB 3", lightStatus: "connect" },
    ],
    title: "A-VCP",
  },
  {
    itemList: [
      { text: "B-VCP", lightStatus: "connect" },
      { text: "B-GCB 1", lightStatus: "connect" },
      { text: "B-GCB 2", lightStatus: "connect" },
      { text: "B-GCB 3", lightStatus: "connect" },
      { text: "B-LBS", lightStatus: "connect" },
      { text: "B-ACB 1", lightStatus: "connect" },
      { text: "B-ACB 2", lightStatus: "connect" },
      { text: "B-ACB 3", lightStatus: "connect" },
    ],
    title: "B-VCP",
  },
];
// 保護電驛
const protectiveRelayList = [
  {
    itemList: [
      { text: "51-1", lightStatus: "connect" },
      { text: "51-2", lightStatus: "connect" },
      { text: "51-3", lightStatus: "connect" },
      { text: "51-4", lightStatus: "connect" },
      { text: "27/59-1", lightStatus: "connect" },
      { text: "81-1", lightStatus: "connect" },
      { text: "50-1", lightStatus: "connect" },
      { text: "50-2", lightStatus: "connect" },
      { text: "50-3", lightStatus: "connect" },
      { text: "50-4", lightStatus: "connect" },
      { text: "27/59-2", lightStatus: "connect" },
      { text: "81-2", lightStatus: "connect" },
      { text: "51N-1", lightStatus: "connect" },
      { text: "51N-2", lightStatus: "connect" },
      { text: "51N-3", lightStatus: "connect" },
      { text: "51N-4", lightStatus: "connect" },
      { text: "27/59-3", lightStatus: "connect" },
      { text: "81-3", lightStatus: "connect" },
      { text: "50N-1", lightStatus: "connect" },
      { text: "50N-2", lightStatus: "connect" },
      { text: "50N-3", lightStatus: "connect" },
      { text: "50N-4", lightStatus: "connect" },
      { text: "27/59-4", lightStatus: "connect" },
      { text: "81-4", lightStatus: "connect" },
      { text: "51G-1", lightStatus: "connect" },
      { text: "51G-2", lightStatus: "connect" },
      { text: "51G-3", lightStatus: "connect" },
      { text: "51G-4", lightStatus: "connect" },
      { text: "59NIT", lightStatus: "connect" },
      { text: "50G-1", lightStatus: "connect" },
      { text: "50G-2", lightStatus: "connect" },
      { text: "50G-3", lightStatus: "connect" },
      { text: "50G-4", lightStatus: "connect" },
      { text: "59NDT", lightStatus: "connect" },
    ],
    title: "MVCB",
  },
  {
    itemList: [
      { text: "51-1", lightStatus: "connect" },
      { text: "51N-1", lightStatus: "connect" },
      { text: "51G-1", lightStatus: "connect" },
      { text: "51-2", lightStatus: "connect" },
      { text: "51N-2", lightStatus: "connect" },
      { text: "51G-2", lightStatus: "connect" },
      { text: "50-1", lightStatus: "connect" },
      { text: "50N-1", lightStatus: "connect" },
      { text: "50G-1", lightStatus: "connect" },
      { text: "50-2", lightStatus: "connect" },
      { text: "50N-2", lightStatus: "connect" },
      { text: "50G-2", lightStatus: "connect" },
    ],
    title: "VCB 1",
  },
  {
    itemList: [
      { text: "51-1", lightStatus: "connect" },
      { text: "51N-1", lightStatus: "connect" },
      { text: "51G-1", lightStatus: "connect" },
      { text: "51-2", lightStatus: "connect" },
      { text: "51N-2", lightStatus: "connect" },
      { text: "51G-2", lightStatus: "connect" },
      { text: "50-1", lightStatus: "connect" },
      { text: "50N-1", lightStatus: "connect" },
      { text: "50G-1", lightStatus: "connect" },
      { text: "50-2", lightStatus: "connect" },
      { text: "50N-2", lightStatus: "connect" },
      { text: "50G-2", lightStatus: "connect" },
    ],
    title: "VCB 2",
  },
];
// 電表資訊
const meterList = [
  {
    iconType: "material-symbols-light:electric-meter-outline",
    itemList: [
      { text: "電壓", value: 23.456, unit: "kV" },
      { text: "電壓_ab", value: 0, unit: "kV" },
      { text: "電流_a", value: 0, unit: "A" },
      { text: "電流_c", value: 0, unit: "A" },
      { text: "視在功率", value: 0, unit: "kW" },
      { text: "總輸入電量", value: 0, unit: "kVA" },
      { text: "總輸入虛功", value: 0, unit: "kVar" },
      { text: "電流", value: 0, unit: "A" },
      { text: "電壓_bc", value: 0, unit: "A" },
      { text: "電流_b", value: 0, unit: "A" },
      { text: "電流_n", value: 0, unit: "A" },
      { text: "功率因數", value: 0, unit: "" },
      { text: "總輸出電量", value: 0, unit: "kVA" },
      { text: "總輸出虛功", value: 0, unit: "kVar" },
      { text: "實功", value: 0, unit: "kW" },
      { text: "實功_ca", value: 0, unit: "kW" },
      { text: "虛功", value: 0, unit: "kVar" },
    ],
    title: "RCP盤頻率表",
  },
  {
    iconType: "material-symbols-light:electric-meter-outline",
    itemList: [
      { text: "電壓", value: 23.456, unit: "kV" },
      { text: "電壓_ab", value: 0, unit: "kV" },
      { text: "電流_a", value: 0, unit: "A" },
      { text: "電流_c", value: 0, unit: "A" },
      { text: "視在功率", value: 0, unit: "kW" },
      { text: "總輸入電量", value: 0, unit: "kVA" },
      { text: "總輸入虛功", value: 0, unit: "kVar" },
      { text: "電流", value: 0, unit: "A" },
      { text: "電壓_bc", value: 0, unit: "A" },
      { text: "電流_b", value: 0, unit: "A" },
      { text: "電流_n", value: 0, unit: "A" },
      { text: "功率因數", value: 0, unit: "" },
      { text: "總輸出電量", value: 0, unit: "kVA" },
      { text: "總輸出虛功", value: 0, unit: "kVar" },
      { text: "實功", value: 0, unit: "kW" },
      { text: "實功_ca", value: 0, unit: "kW" },
      { text: "虛功", value: 0, unit: "kVar" },
    ],
    title: "VCB-A",
  },
  {
    iconType: "material-symbols-light:electric-meter-outline",
    itemList: [
      { text: "電壓", value: 23.456, unit: "kV" },
      { text: "電壓_ab", value: 0, unit: "kV" },
      { text: "電流_a", value: 0, unit: "A" },
      { text: "電流_c", value: 0, unit: "A" },
      { text: "視在功率", value: 0, unit: "kW" },
      { text: "總輸入電量", value: 0, unit: "kVA" },
      { text: "總輸入虛功", value: 0, unit: "kVar" },
      { text: "電流", value: 0, unit: "A" },
      { text: "電壓_bc", value: 0, unit: "A" },
      { text: "電流_b", value: 0, unit: "A" },
      { text: "電流_n", value: 0, unit: "A" },
      { text: "功率因數", value: 0, unit: "" },
      { text: "總輸出電量", value: 0, unit: "kVA" },
      { text: "總輸出虛功", value: 0, unit: "kVar" },
      { text: "實功", value: 0, unit: "kW" },
      { text: "實功_ca", value: 0, unit: "kW" },
      { text: "虛功", value: 0, unit: "kVar" },
    ],
    title: "MVCB1盤",
  },
  {
    iconType: "material-symbols-light:electric-meter-outline",
    itemList: [
      { text: "電壓", value: 23.456, unit: "kV" },
      { text: "電壓_ab", value: 0, unit: "kV" },
      { text: "電流_a", value: 0, unit: "A" },
      { text: "電流_c", value: 0, unit: "A" },
      { text: "視在功率", value: 0, unit: "kW" },
      { text: "總輸入電量", value: 0, unit: "kVA" },
      { text: "總輸入虛功", value: 0, unit: "kVar" },
      { text: "電流", value: 0, unit: "A" },
      { text: "電壓_bc", value: 0, unit: "A" },
      { text: "電流_b", value: 0, unit: "A" },
      { text: "電流_n", value: 0, unit: "A" },
      { text: "功率因數", value: 0, unit: "" },
      { text: "總輸出電量", value: 0, unit: "kVA" },
      { text: "總輸出虛功", value: 0, unit: "kVar" },
      { text: "實功", value: 0, unit: "kW" },
      { text: "實功_ca", value: 0, unit: "kW" },
      { text: "虛功", value: 0, unit: "kVar" },
    ],
    title: "MVCB2盤",
  },
];

export {
  equipmentStatusList,
  equipmentVcpList,
  lightStatus,
  meterList,
  protectiveRelayList,
};
